name: MineMillion
version: '${project.version}'
main: dev.lotnest.minemillion.MineMillionPlugin
api-version: 1.19
authors: [ Lotnest ]
website: https://discord.gg/6vrHK87
libraries:
  - org.projectlombok:lombok:1.18.24
  - org.apache.commons:commons-lang3:3.12.0
  - com.google.code.gson:gson:2.10.1
  - com.zaxxer:HikariCP:5.0.1
  - org.jooq:jooq:3.17.6
  - org.jetbrains:annotations:24.0.0